In [1]:
import pandas as pd 
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("/Users/pruth/Downloads/diamonds.csv")

In [3]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
x,xt,y,yt=train_test_split(df[['carat', 'depth', 'table', 'x', 'y',
       'z', 'cut', 'color', 'clarity']],df["price"],train_size=0.8,random_state=1)

In [5]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_t=pd.DataFrame(scaler.fit_transform(x[["carat","depth","table","x","y","z"]]),columns=scaler.get_feature_names_out())
xt_t=pd.DataFrame(scaler.fit_transform(xt[["carat","depth","table","x","y","z"]]),columns=scaler.get_feature_names_out())

In [6]:
# from sklearn.preprocessing import OneHotEncoder
# one=OneHotEncoder(sparse_output=False)
# x_t=pd.DataFrame(one.fit_transform(x[["carat","depth","table","x","y","z"]]),columns=one.get_feature_names_out(),index=x.index)
# xt_t=pd.DataFrame(one.fit_transform(xt[["carat","depth","table","x","y","z"]]),columns=one.get_feature_names_out(),index=xt.index)

In [7]:
x_t

          carat     depth     table         x         y         z
0     -0.813799  0.386083 -1.991090 -0.824818 -0.834724 -0.784375
1      0.678822 -0.870973  0.689861  0.944278  0.866469  0.779256
2     -0.792777 -0.801137 -0.650615 -0.798148 -0.747928 -0.840722
3      0.510639  0.525756  0.689861  0.650910  0.588723  0.680649
4     -0.204137 -2.337539  1.136686  0.099735  0.120027 -0.164557
...         ...       ...       ...       ...       ...       ...
43147 -0.204137  0.735265  0.689861 -0.149183 -0.105641 -0.037776
43148 -0.834822  1.503467 -0.203789 -0.904827 -0.938878 -0.770288
43149  0.237342  0.665429  2.477162  0.286423  0.232861  0.342567
43150  0.804959 -0.032936 -0.650615  0.944278  0.944585  0.934211
43151 -1.003005 -0.591627 -0.650615 -1.171525 -1.129829 -1.192891

[43152 rows x 6 columns]

In [8]:
cat=x[["cut","color","clarity"]]

In [9]:
cat1=xt[["cut","color","clarity"]]

In [10]:
from sklearn.preprocessing import OrdinalEncoder
ordinal=OrdinalEncoder()

In [11]:
x_t[["cut","color","clarity"]]=pd.DataFrame(ordinal.fit_transform(cat))

In [12]:
xt_t[["cut","color","clarity"]]=pd.DataFrame(ordinal.transform(cat1))

In [13]:
x_t

,carat,depth,table,x,y,z,cut,color,clarity
0,-0.813799,0.386083,-1.991090,-0.824818,-0.834724,-0.784375,2.0,2.0,6.0
1,0.678822,-0.870973,0.689861,0.944278,0.866469,0.779256,3.0,2.0,3.0
2,-0.792777,-0.801137,-0.650615,-0.798148,-0.747928,-0.840722,2.0,2.0,4.0
3,0.510639,0.525756,0.689861,0.650910,0.588723,0.680649,3.0,1.0,6.0
4,-0.204137,-2.337539,1.136686,0.099735,0.120027,-0.164557,1.0,1.0,4.0
...,...,...,...,...,...,...,...,...,...
43147,-0.204137,0.735265,0.689861,-0.149183,-0.105641,-0.037776,4.0,5.0,5.0
43148,-0.834822,1.503467,-0.203789,-0.904827,-0.938878,-0.770288,1.0,1.0,3.0
43149,0.237342,0.665429,2.477162,0.286423,0.232861,0.342567,4.0,3.0,5.0
43150,0.804959,-0.032936,-0.650615,0.944278,0.944585,0.934211,2.0,6.0,4.0
43151,-1.003005,-0.591627,-0.650615,-1.171525,-1.129829,-1.192891,2.0,1.0,6.0

In [14]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [15]:
x_t.isna().sum()

carat      0
depth      0
table      0
x          0
y          0
z          0
cut        0
color      0
clarity    0
dtype: int64

In [16]:
from sklearn.neighbors import KNeighborsRegressor
GNB=KNeighborsRegressor()
GNB.fit(x_t,y)
predict=GNB.predict(xt_t)
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(yt,predict))

390.1739340007416

In [17]:
predict=GNB.predict(xt_t)

In [18]:
yt

2714      564
14653    5914
52760    2562
48658     537
14812    5964
         ...
49568    2131
32163     787
52459    2516
15265    6129
43028    1372
Name: price, Length: 10788, dtype: int64

In [22]:
!git remote set-url origin https://github.com/pruthvipatil26/ML-Case-Studies-.git
!git remote -v

origin	https://github.com/pruthvipatil26/ML-Case-Studies-.git (fetch)
origin	https://github.com/pruthvipatil26/ML-Case-Studies-.git (push)

In [25]:
!git add "Dimand price prediction .ipynb"

warning: in the working copy of 'Classification/NLP/Case Studies/Dimand price prediction .ipynb', LF will be replaced by CRLF the next time Git touches it

In [26]:
!git commit -m "Add Email Spam Ham Detection notebook"
!git push -u origin main

[main 2ae697b] Add Email Spam Ham Detection notebook
 1 file changed, 69 insertions(+), 61 deletions(-)
branch 'main' set up to track 'origin/main'.

To https://github.com/pruthvipatil26/ML-Case-Studies-.git
 * [new branch]      main -> main